#!/bin/sh

echo "Installing python dependencies via pip..."
pip install pycrypto
pip install fdb

echo "Setting firebird SYSDBA user..."

dpkg-reconfigure firebird2.5-super

echo "Setting up firebird database..."
echo "Please enter your SYSDBA password:"

read password
echo "add SCVREPO -pw $password" | gsec -user SYSDBA -pass $password
cat "/tmp/repo_database.sql" | isql-fb -user SYSBDA -pass $password 
rm "/tmp/repo_database.sql"

/etc/init.d/apache2 start

echo "WARNING: Change 
