CREATE TABLE CSS ( 
  CSS_ID INT NOT NULL,
  CSS_SELECTOR VARCHAR(15) NOT NULL,
  CSS_MOD_ID INT,
  CSS_WGT_ID INT,
  CSS_SESSION VARCHAR(32),
  CSS_TAG VARCHAR(20) NOT NULL,
  CSS_VALUE VARCHAR(50) NOT NULL,
  CONSTRAINT PK_CSS PRIMARY KEY (CSS_ID)
);
CREATE TABLE CSSSESSION ( 
  CSE_SESSION VARCHAR(32) NOT NULL,
  CSE_FILE VARCHAR(50) NOT NULL,
  CONSTRAINT PK_CSSSESSION PRIMARY KEY(CSE_SESSION,CSE_FILE)
);
